meus_produtos = {
    1: "entrada",
    2: "ades",
    3: "coca-cola",
    4: "guarana",
    5: "fanta",
    6: "pepsi",
    7: "leite",
    8: "redbull",
    9: "monster",
    10: "tnt",
    11: "kuat",
    12: "guarana jesus",
    13: "suco de uva integral",
    14: "arroz",
    15: "feijao",
    16: "macarrao",
    17: "farinha",
    18: "acucar",
    19: "sal",
    20: "miojo",
    21: "cafe",
    22: "biscoito",
    23: "salgadinho",
    24: "chocolate",
    25: "bombom",
    26: "alface",
    27: "tomate",
    28: "abobora",
    29: "batata",
    30: "pimenta",
    31: "pepino",
    32: "chuchu",
    33: "jilo",
    34: "cebola",
    35: "alho",
    36: "maca",
    37: "banana",
    38: "morango",
    39: "uva",
    40: "abacaxi",
    41: "goiaba",
    42: "pera",
    43: "melancia",
    44: "mamao",
    45: "melao",
    46: "limao",
    47: "brocolis",
    48: "cenoura",
    49: "abobrinha",
    50: "nugget",
    51: "pizza",
    52: "hamburguer",
    53: "frango",
    54: "porco",
    55: "picanha",
    56: "costela",
    57: "contra-file",
    58: "queijo",
    59: "iogurte",
    60: "caixa",
    61: "escova de dentes",
    62: "pasta de dente",
    63: "detergente",
    64: "agua sanitaria",
    65: "fio dental",
    66: "sabonete",
    67: "shampoo",
    68: "condicionador",
    69: "esponja",
    70: "sabao em po",
    71: "amaciante",
    72: "desinfetante",
    73: "papel higienico",
    74: "lenco umedecido",
}